server:
  port: ${PORT:8080}
spring:
  config:
    activate:
      on-profile: prod

  ai:
    ollama:
      chat:
        enabled: false
      embedding:
        enabled: false
    openai:
      chat:
        enabled: true
        base-url: https://generativelanguage.googleapis.com/v1beta/openai/
        api-key: ${GOOGLE_AI_API_KEY}
        options:
          model: ${GOOGLE_AI_MODEL:gemini-1.5-flash}
      embedding:
        enabled: true
        base-url: https://generativelanguage.googleapis.com/v1beta/openai/
        api-key: ${GOOGLE_AI_API_KEY}
        options:
          model: gemini-embedding-001

  data:
    mongodb:
      uri: ${MONGODB_URI}

logging:
  level:
    org.springframework.ai: INFO
    com.aicareerforge: INFO
